---
apiVersion: v1
kind: Secret
metadata:
  name: pytorch-operator-token
  namespace: kubeflow
  annotations:
    kubernetes.io/service-account.name: pytorch-operator
type: kubernetes.io/service-account-token