---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-dashboard
  name: tf-job-dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-operator
  name: tf-job-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: tf-job-operator-token
  namespace: kubeflow
  annotations:
    kubernetes.io/service-account.name: tf-job-operator
type: kubernetes.io/service-account-token  
