---
apiVersion: v1
kind: Secret
metadata:
  name: service-account-token
  namespace: kubeflow
  annotations:
    kubernetes.io/service-account.name: profiles-controller-service-account
type: kubernetes.io/service-account-token  