apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  serviceName: service
  selector:
    matchLabels:
      app: application-controller
  template:
    metadata:
      labels:
        app: application-controller
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: manager
        command:
        - /root/manager
        image: gcr.io/kubeflow-images-public/kubernetes-sigs/application
        imagePullPolicy: Always
        env:
        # TODO(https://github.com/kubeflow/manifests/issues/1043)
        # Do we really need this?
        - name: project
          value: $(project)
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: application-controller-service-account-token
          readOnly: true
      volumes:
      - name: application-controller-service-account-token
        secret:
          defaultMode: 420
          secretName: application-controller-service-account-token    
  volumeClaimTemplates: []
