apiVersion: batch/v1
kind: Job
metadata:
  name: katib-cert-generator
  namespace: kubeflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:      
      containers:
        - name: cert-generator
          image: docker.io/kubeflowkatib/cert-generator
          imagePullPolicy: Always
          env:
            - name: KATIB_CORE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: katib-cert-generator-token
            readOnly: true        
      restartPolicy: Never
      volumes:
      - name: katib-cert-generator-token
        secret:
          defaultMode: 420
          secretName: katib-cert-generator-token
  backoffLimit: 4
