---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    serving.knative.dev/release: v0.14.3
  name: controller
  namespace: knative-serving
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-token
  namespace: knative-serving
  annotations:
    kubernetes.io/service-account.name: controller
type: kubernetes.io/service-account-token